# frozen_string_literal: true

# Uncomment the next line to define a global platform for your project
platform :ios, "14"

plugin "cocoapods-swift-packager",
  packages: [
    {
      repositoryURL: "https://github.com/pointfreeco/swift-composable-architecture",
      requirement: {
        kind: "upToNextMajorVersion",
        minimumVersion: "0.9.0"
      }, # XCRemoteSwiftPackageReference
      products: [
        {name: "ComposableArchitecture"}
      ] # XCSwiftPackageProductDependency, also PBXBuildFile for product
    }
  ],
  local_packages: [
    {path: "relative/to/Podfile"} # just adds a PBXFileReference to correct group, then a build file
  ],
  pod_dependencies: {
    ExampleLibrary: [
      "ComposableArchitecture"
    ] # add packageProductDependencies to PBXNativeTarget, add build file to PBXFrameworksBuildPhase.
    # also: ensure swift import path (optionally: / framework search paths / header search paths are correct)
  }

target "example" do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for example
  pod "ExampleLibrary", path: "ExampleLibrary"
end
